# Generated by Django 5.2.12 on 2026-03-18 06:51

import django.db.models.deletion
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surgeries', '0002_alter_operatingroom_id_alter_surgery_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.FileField(upload_to=videos.models.video_upload_path)),
                ('video_hash', models.CharField(blank=True, max_length=256)),
                ('recording_start', models.DateTimeField()),
                ('recording_end', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('storage_type', models.CharField(choices=[('WORM', 'WORM'), ('CLOUD', 'Cloud'), ('ARCHIVE', 'Archive')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surgery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='surgeries.surgery')),
            ],
        ),
    ]
