# Generated by Django 5.2.12 on 2026-04-06 06:14

import cloudinary_storage.storage
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeryvideo',
            name='video_path',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=videos.models.video_upload_path),
        ),
    ]
