# Generated by Django 5.2.12 on 2026-04-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_surgeryvideo_video_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgeryvideo',
            name='video_path',
        ),
        migrations.AddField(
            model_name='surgeryvideo',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
