# Generated by Django 5.2.12 on 2026-03-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_department_id_alter_user_id'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('hospital_admin', 'Hospital Admin'), ('department_head', 'Department Head'), ('student', 'Student'), ('external_entity', 'External Entity'), ('system_admin', 'System Admin')], db_index=True, default='doctor', max_length=50),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'department'], name='accounts_us_role_dacc92_idx'),
        ),
    ]
