# Generated by Django 5.2.12 on 2026-03-19 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_video', 'View Video'), ('export_video', 'Export Video'), ('create_surgery', 'Create Surgery'), ('update_surgery', 'Update Surgery'), ('delete_surgery', 'Delete Surgery'), ('access_denied', 'Access Denied')], max_length=50)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx')],
            },
        ),
    ]
