# Generated by Django 5.2.12 on 2026-03-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_video', 'View Video'), ('export_video', 'Export Video'), ('upload_video', 'Upload Video'), ('create_surgery', 'Create Surgery'), ('update_surgery', 'Update Surgery'), ('delete_surgery', 'Delete Surgery'), ('access_denied', 'Access Denied')], max_length=50),
        ),
    ]
