# Generated by Django 5.2.12 on 2026-03-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surgeries', '0002_alter_operatingroom_id_alter_surgery_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('video_not_recorded', 'Video Not Recorded'), ('camera_offline', 'Camera Offline'), ('consent_missing', 'Consent Missing'), ('video_tampered', 'Video Tampered'), ('upcoming_surgery', 'Upcoming Surgery')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('surgery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='surgeries.surgery')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('surgery', 'alert_type')},
            },
        ),
    ]
